#!/bin/bash

IFS=$'\n'
for l in `getent passwd | grep /home/`; do
  user=`echo $l | cut -d: -f1`
  gid=`echo $l | cut -d: -f4`
  home=`echo $l | cut -d: -f6`
  voxel=`echo $home | sed -e 's@/home/@/voxel/@'`
  pixel=`echo $home | sed -e 's@/home/@/pixel/@'`
  if [ ! -d $home ]; then
    echo creating $home
    mkdir -p `dirname $home`
    cp -r /etc/skel $home
    chown -R $user:$gid $home
    # create the links to the data dirs, if not on one of those servers
    if [ `hostname` != voxel.jouy.inra.fr ] && [ `hostname` != pixel.jouy.inra.fr ]; then
      ln -s $voxel/images $home/images
      ln -s $pixel/analyse $home/analyse
    fi
  else
    chown $user:$gid $home
  fi
done
