#!/usr/bin/env python

from datetime import datetime, timedelta
import re, sys
from optparse import OptionParser

parser = OptionParser(usage = '"Usage: select_too_frequent_snapshots [snap...]"')
opts, args = parser.parse_args()

if not args:
  # read the snap names from stdin
  args = [l.strip() for l in sys.stdin.readlines()]

now = datetime.now()

date_format = re.compile('@(\d+)-(\d+)-(\d+)_(\d+)h(\d+)m*(\d*)$')
prev = None

for snap in args:
  # search for the date in the snap name
  res = date_format.search(snap)
  if not res:
    # just ignore this one
    continue
  # just keep the date
  snap_date = datetime(*[int(v) for v in res.groups() if v != '']).date()
  
  if prev == snap_date:
    print snap
  else:
    prev = snap_date
    