#!/usr/bin/env python

from datetime import datetime, timedelta
import re, sys
from optparse import OptionParser

parser = OptionParser(usage = '"Usage: select_old_snapshots snap..."')
parser.add_option("-o", "--older-than", type="int", dest="older", default=60, help="select snapshots older than X days (default: 60)")
opts, args = parser.parse_args()

if not args:
  # read the snap names from stdin
  args = [l.strip() for l in sys.stdin.readlines()]

older = timedelta(days=opts.older)
now = datetime.now()

date_format = re.compile('@(\d+)-(\d+)-(\d+)_(\d+)h(\d+)m*(\d*)$')

for snap in args:
  # search for the date in the snap name
  res = date_format.search(snap)
  if not res:
    # just ignore this one
    continue
  snap_date = datetime(*[int(v) for v in res.groups() if v != ''])
  if now - snap_date > older:
    print snap
    