#!/bin/bash

# set -ex

if [ $# -lt 2 ]; then
  echo "usage: shareacl directory user [user ...]"
  exit 1
fi

dir=$1
shift
users=$@

for u in $users; do
  if [ `uname` == "SunOS" ]; then
    chmod -R A+user:$u:rwxpdDaARWcCos:fd:allow "$dir"
  else
    setfacl -R -P -m u:$u:rwx "$dir"
    setfacl -R -P -m d:u:$u:rwx "$dir"
  fi
done

if [ `uname` != "SunOS" ]; then
  setfacl -R -P -m m::rwx "$dir"
  setfacl -R -P -m d:m::rwx "$dir"
fi
