#!/bin/bash

# set -ex

if [ $# -lt 2 ]; then
  echo "usage: shareacl directory user [user ...]"
  exit 1
fi

dir=$1
shift
users=$@

if [ `uname` == "SunOS" ]; then
  for u in $users; do
    # there is no -P option in chmod, so we must use find to avoid symlinks
    gfind "$dir" -type f -print0 | gxargs -0 chmod A+user:$u:rwxpdDaARWcCos:fd:allow 
    gfind "$dir" -type d -print0 | gxargs -0 chmod A+user:$u:rwxpdDaARWcCos:fd:allow 
  done
else
  for u in $users; do
    setfacl -R -P -m u:$u:rwx "$dir"
    setfacl -R -P -m d:u:$u:rwx "$dir"
  done
  setfacl -R -P -m m::rwx "$dir"
  setfacl -R -P -m d:m::rwx "$dir"
fi
