#!/bin/sh

if [ ! -f ~/.ssh/id_rsa.pub ] ; then
    mkdir -p ~/.ssh/
    ssh-keygen -t rsa -N "" -f ~/.ssh/id_rsa
fi

ssh $1 \
	mkdir -p \~/.ssh/ \; \
	echo `cat ~/.ssh/id_rsa.pub`\>\> \~/.ssh/authorized_keys \; \
	chmod 600 \~/.ssh/authorized_keys
