#!/usr/bin/bash

export LC_ALL=C
export PATH=$PATH:/usr/local/bin

# messages levels
QUIET=0
VERBOSE=2

# default retention values
RETENTION=-1
FREQ_RETENTION=10
# let the user change them
if [ -f /etc/zbackup ]; then
  source /etc/zbackup
fi

# command line parsing
DEST=
ZONES=
MESSAGE_LEVEL=1
DESTROY=false
BACKUP=true
FORCE=false
INVALID_OPT=false
RUNNING_ZONES=`zoneadm list | egrep -v '^global$'`
while [ $# != 0 ]; do
  while getopts ":advqfBh" opt; do
    case $opt in
      a)
        ZONES="$ZONES $RUNNING_ZONES"
        ;;
      d)
        DESTROY=true
        ;;
      v)
        MESSAGE_LEVEL=$VERBOSE
        ;;
      q)
        MESSAGE_LEVEL=$QUIET
        ;;
      f)
        FORCE=true
        ;;
      B)
        BACKUP=false
        ;;
      h)
        INVALID_OPT=true
        ;;
      \?)
        echo "Invalid option: -$OPTARG" >&2
        INVALID_OPT=1
        ;;
    esac
  done
  shift $((OPTIND-1))
  OPTIND=1
  if [ "$DEST" == "" ]; then
    DEST=$1
  else
    ZONES="$ZONES $1"
  fi
  shift
done

if $INVALID_OPT || [ "$DEST" == "" ] || [ "$ZONES" == "" ]; then
  echo "usage: zbackup host [options] zone..."
  echo "       zbackup host [options] -a"
  echo
  echo "options:"
  echo "  -a  process all the running zones"
  echo "  -d  destroy too old and too frequent snapshots"
  echo "  -v  verbose mode"
  echo "  -q  quiet mode"
  echo "  -f  allow to specify non running zones"
  echo "  -B  don't run the backup (useful with -d)"
  echo "  -h  display this message and exit"
  exit 1
fi

set -e

function syncfs {
  pool=$1
  Z=$2
  snap=$3
  rcvflags=
  if [ $MESSAGE_LEVEL != $QUIET ]; then
    rcvflags="$rcvflags -v"
  fi
  # get the last snapshot on the remote host and use it for an incremental update, if possible
  distsnap=`ssh $DEST zfs list -r -s creation -o name -H $pool/zones/$Z | grep $pool/zones/$Z@ | tail -1 | cut -d@ -f2`
  if [ -z "$distsnap" ]; then
    zfs send -R $pool/zones/$Z@$snap | ssh -c arcfour $DEST zfs receive -dF $rcvflags $pool
  else
    zfs send -RI $distsnap $pool/zones/$Z@$snap | ssh -c arcfour $DEST zfs receive -dF $rcvflags $pool
  fi

}

function message {
  level=$1
  shift
  if [ $level -ge $MESSAGE_LEVEL ]; then
    echo == $@ == >&2
  fi
}


if $BACKUP; then
  # first sync the fs to make the freeze as short as possible - zfs snapshot syncs the fs, if there is
  # not much to sync, the snapshot is done quicker
  sync
  
  # create the snapshots - this step is important, and has very little chance to fail
  snap=`date +%Y-%m-%d_%Hh%Mm%S`
  for Z in $ZONES; do
    message $VERBOSE snapshotting $Z
    # do we have a file system for this zone on data zpool
    if zfs list data/zones/$Z 2>/dev/null >/dev/null; then
      # we have two pools to snapshot at the same time - we have to freeze the zone
      # to be able to to that.
      running_processes=`ps -o s= -o pid= -z $Z | grep -v T | awk '{print $2}'`
      kill -s SIGSTOP $running_processes
      zfs snapshot -r rpool/zones/$Z@$snap
      zfs snapshot -r data/zones/$Z@$snap
      kill -s SIGCONT $running_processes
    else
      # just take the snapshot
      zfs snapshot -r rpool/zones/$Z@$snap
    fi
  done
  
  
  # copy the fs to the remote host
  for Z in $ZONES; do
    message $VERBOSE copying $Z to $DEST
    syncfs rpool $Z $snap
    if zfs list data/zones/$Z 2>/dev/null >/dev/null; then
        syncfs data $Z $snap
    fi
  done
fi

if $DESTROY; then
  echo == this feature is not fully implemented yet          ==
  echo == it only print the names of the snapshot to destroy ==
  for Z in $ZONES; do
    message $VERBOSE destroying $Z snapshots
    # determine the retention times
    retention=`zfs get -o value -H zbackup:retention rpool/zones/$Z`
    if [ "$retention" == "-" ]; then
      retention=$RETENTION
    fi
    freq_retention=`zfs get -o value -H zbackup:freq_retention rpool/zones/$Z`
    if [ "$freq_retention" == "-" ]; then
      freq_retention=$FREQ_RETENTION
    fi
    message $VERBOSE rpool/zones/$Z retention times are $retention/$freq_retention
    # remote snapshots first
    zfs list -rHo name rpool/zones/$Z | select_old_snapshots -o $retention # | xargs -L1 -t ssh $DEST zfs destroy
    zfs list -rHo name rpool/zones/$Z | select_too_frequent_snapshots | select_old_snapshots -o $freq_retention # | xargs -L1 -t ssh $DEST zfs destroy
    # then local ones
    zfs list -rHo name rpool/zones/$Z | select_old_snapshots -o $retention # | xargs -L1 -t zfs destroy
    zfs list -rHo name rpool/zones/$Z | select_too_frequent_snapshots | select_old_snapshots -o $freq_retention # | xargs -L1 -t zfs destroy
    
    # do we have a file system for this zone on data zpool
    if zfs list data/zones/$Z 2>/dev/null >/dev/null; then
      # determine the retention times
      retention=`zfs get -o value -H zbackup:retention data/zones/$Z`
      if [ "$retention" == "-" ]; then
        retention=$RETENTION
      fi
      freq_retention=`zfs get -o value -H zbackup:freq_retention data/zones/$Z`
      if [ "$freq_retention" == "-" ]; then
        freq_retention=$FREQ_RETENTION
      fi
      message $VERBOSE data/zones/$Z retention times are $retention/$freq_retention
      # remote snapshots first
      zfs list -rHo name data/zones/$Z | select_old_snapshots -o $retention # | xargs -L1 -t ssh $DEST zfs destroy
      zfs list -rHo name data/zones/$Z | select_too_frequent_snapshots | select_old_snapshots -o $freq_retention # | xargs -L1 -t ssh $DEST zfs destroy
      # then local ones
      zfs list -rHo name data/zones/$Z | select_old_snapshots -o $retention # | xargs -L1 -t zfs destroy
      zfs list -rHo name data/zones/$Z | select_too_frequent_snapshots | select_old_snapshots -o $freq_retention # | xargs -L1 -t zfs destroy
    fi
  done
fi

exit 0










# nom du système de fichier à sauvegarder
backupfs=$1
remote_host=$2
remotefs=$3

if [[ -z $backupfs ]] || [[ -z $remote_host ]] || [[ -z $remotefs ]]
then
     echo usage: $0 backupfs remote_host remotefs
     exit 1
fi


function lzfs {
  pfexec /usr/sbin/zfs $@
}

function rzfs {
  ssh $remote_host pfexec /usr/sbin/zfs $@
}

function crzfs {
#  /usr/local/bin/tamp | /usr/local/bin/pv -ftbri 10000000 | ssh $remote_host "/usr/local/bin/tamp -d | pfexec /usr/sbin/zfs $@"
#  /usr/local/bin/pv -ftbri30 -cN raw | /usr/local/bin/tamp | /usr/local/bin/pv -ftbri30 -cN comp | ssh $remote_host "/usr/local/bin/tamp -d | pfexec /usr/sbin/zfs $@"
#  /usr/local/bin/pv -ftbri30 | ssh $remote_host "pfexec /usr/sbin/zfs $@"
  ssh $remote_host pfexec /usr/sbin/zfs $@
}


# avant toute chose, prendre un snapshot.
# Peu importe qu'on puisse le transmettre ou pas, il faut le creer !

# On détermine le nom du prochain snapshot.
new_snapshot=`date +backup_%Y-%m-%d_%Hh%M`
while lzfs list $backupfs@$new_snapshot 2> /dev/null > /dev/null ; do
  echo "Patienter SVP"
  sleep 1
  new_snapshot=`date +backup_%Y-%m-%d_%Hh%M`
done
echo "Nom du nouveau snapshot: $new_snapshot"

# On effectue un nouveau snapshot
lzfs snapshot -r $backupfs@$new_snapshot


# pour éviter de figer le systeme distant pendant plusieurs secondes, on le force à synchroniser les systèmes de fichier.
ssh $remote_host "while [ 1 ]; do sync; done" &
sync_pid=$!

if [[ "$backupfs" =~ "/" ]]; then
  rbackupfs=$remotefs/`echo $backupfs | cut -d/ -f 2-`
else
  rbackupfs=$remotefs
fi

if rzfs list $rbackupfs 2> /dev/null > /dev/null ; then
  # nom de la dernière sauvegarde commencée
  last_snapshot=`rzfs list -rH -t snapshot -o name -s creation $rbackupfs | gegrep "^$rbackupfs@" | cut -d @ -f2 | tail -1`
  echo "Le dernier snapshot trouvé est : $last_snapshot"

  # On s'assure que tous les systèmes de fichier sur le serveur de sauvegarde sont tous au même état (date) de 
  # dernière sauvegarde, sinon on met à jour les systèmes de fichier dont les sauvegardes sont plus anciennes.
  #

  # On parcours un à un les systèmes de fichier à sauvegarder
  for fs in `lzfs list -H -o name -r -t filesystem $backupfs`; do
  
    rfs=`echo $fs | sed "s#^$backupfs#$remotefs#"`

    # on récupère le plus recent des snapshots sur le serveur des sauvegardes
    dist_fs_last_snap=`rzfs list -rH -t snapshot -o name -s creation $rfs | cut -d @ -f2 | tail -1`
  
    if [ "$dist_fs_last_snap" != "" ] ; then
      # Le système de fichier existe sur le serveur de sauvegarde, s'il n'est pas à jour, la différence est envoyé.
      if [ "$dist_fs_last_snap" != "$last_snapshot" ] ; then
        echo "Envoi du snapshot $fs@($dist_fs_last_snap->$last_snapshot)"
        rzfs rollback -r $fs@$dist_fs_last_snap 
        lzfs send -I $dist_fs_last_snap $fs@$last_snapshot | crzfs receive -uF $fs
      fi
    else
    echo le systeme de fichier nexiste pas sur le serveur de sauvegarde
      # le systeme de fichier n'existe pas sur le serveur de sauvegarde
      if lzfs list $fs@$last_snapshot 2> /dev/null > /dev/null ; then
        # On test l'existence du dernier snapshot du serveur de sauvegarde, s'il existe, il est transféré vers le serveur distant
        echo "Envoi du snapshot $fs@(X->$last_snapshot)"
        lzfs send -R $fs@$last_snapshot | crzfs receive -uvd $remotefs
      fi
    fi

  done

  # On effectue un rollback du dernier snapshot sur le serveur de sauvegarde
  rzfs rollback -r $rbackupfs@$last_snapshot

  # On envoie la différence entre le nouveau snapshot et l'ancienne version sur le serveur de sauvegarde
  echo "Envoi du snapshot $backupfs@($last_snapshot->$new_snapshot)"
  lzfs send -RI $last_snapshot $backupfs@$new_snapshot | crzfs receive -udv $remotefs

else
  # premiere copie
  # On envoie tout ca sur le serveur de sauvegarde
  echo "Envoi du snapshot $backupfs@(X->$new_snapshot)"
  rzfs create $remotefs
  rzfs umount $remotefs
  lzfs send -R $backupfs@$new_snapshot | crzfs receive -udFv $remotefs
fi

rzfs inherit -r mountpoint $remotefs
rzfs mount -a

kill $sync_pid
