#!/usr/bin/bash

set -e
export LC_ALL=C

if [ $# -lt 2 ]; then
  echo "usage: zmigrate host zone..."
  echo "       zmigrate host -a"
  exit 1
fi

DEST=$1
shift
ZONES=$@

# running zones
if [[ "$ZONES" == "-a" ]]; then
  ZONES=`zoneadm list | egrep -v '^global$'`
fi

########################################################
# utility functions
########################################################

function zshutdown {
  Z=$1
  zlogin $Z shutdown -i0 -g0 -y
  for i in {12..1}; do
    if [ -z "`zoneadm -z $Z list -p | grep :installed:`" ]; then
      echo waiting for $Z to shutdown. $i attempts left before killing...
      sleep 5
    else
      echo $Z halted.
      return 0
    fi
  done
  echo killing $Z...
  zoneadm -z $Z halt
  echo $Z halted.
}

########################################################
# copy the zone config on the remote host
########################################################

# zonecfg -z $Z export > /tmp/$Z.zone
# scp /tmp/$Z.zone $DEST:/tmp/$Z.zone
# ssh $DEST zonecfg -z $Z -f /tmp/$Z.zone
# ssh $DEST zoneadm -z $Z list

# move rctl sections at the end because of bug http://bugs.opensolaris.org/bugdatabase/view_bug.do?bug_id=6565738

for Z in $ZONES; do
  echo ========== Copying $Z configuration to the destination host... ========== 

  zonecfg -z $Z export | python -c 'import sys
last=""
rctl=False
for l in sys.stdin.readlines():
  if l == "add rctl\n":
    rctl=True
  if rctl:
    last+=l
  else:
    print l,
  if l == "end\n":
    rctl=False
print last,
  ' | ssh $DEST zonecfg -z $Z
  ssh $DEST zoneadm -z $Z list

  echo  ========== $Z copied. ========== 

  ########################################################
  # pre sync filesystems, to decrease down time
  ########################################################

  echo  ========== Pre-syncing $Z pools on the destination host... ========== 

  /usr/local/bin/zbackup $DEST $Z -C

  echo ==========  $Z pool pre-synced. ========== 

  ########################################################
  # stop the zone and fully sync the file systems
  ########################################################

  echo  ========== Syncing $Z pools on the destination host... ========== 

  zshutdown $Z
  zoneadm -z $Z detach

  /usr/local/bin/zbackup $DEST $Z -Cf

  echo  ========== $Z pool synced. ========== 

  ########################################################
  # move the zone to the new host
  ########################################################

  echo  ========== Moving $Z on the destination host... ========== 

  ssh $DEST zoneadm -z $Z attach -u
  ssh $DEST zoneadm -z $Z boot
  zonecfg -z $Z delete -F

  echo  ========== $Z moved. ========== 
done
