#!/usr/bin/env python

import sys, commands, re, os
from optparse import OptionParser
parser = OptionParser()
parser.add_option("-d", "--dry-run", action="store_true", dest="dryRun", default=False, help="just display rsync commnad, don't execute it.")
parser.add_option("-v", "--verbose", action="store_true", dest="verbose", default=False)
(options, args) = parser.parse_args()

maxIt = 5

def removeSlash(s) :
    if s and s[-1] == "/" :
	s = removeSlash(s[:-1])
    return s


for fName in args :
	f = file(fName)
	for line in f :
		if not line.startswith("#") and not re.match(r'^\s*$', line) :
			lineTab = re.split("\t+", line)
			url = removeSlash(lineTab[0].strip())
			localDir = lineTab[1].strip()
			opt = " ".join(lineTab[2:]).strip()
			command = "rsync -av --delete-after %s '%s' '%s'" % (opt, url, localDir)
			
			if options.dryRun :
			    sys.stderr.write(command+"\n")
			else :
			
			    for it in range(maxIt) :
				if options.verbose :
				    sys.stderr.write(command+"\n")
				(status, output) = commands.getstatusoutput(command)
				if options.verbose :
					sys.stderr.write(output+"\nstatus="+str(status)+"\n\n")
				
				# remove non informative lines
				if status == 0 :
					newOutput = ""
					for syncLine in output.splitlines() :
						if re.match(r'^/\S+', syncLine) :
							newOutput += syncLine
					# print [newOutput]
					if newOutput == "" :
						break
				else :
					print output
			
	f.close()
if not options.dryRun :
    os.system("find /var/www/html/mdk/ -name MD5SUM -exec rm -f {} \;")
